<?php

namespace App\Console\Commands;

use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Statamic\Facades\Fieldset;
use Statamic\Fields\Fields;

#[Signature('content:catalog')]
#[Description('Generate the agent content catalog from the page-builder fieldset so the content agent always knows the legal sections and fields.')]
class BuildAgentCatalog extends Command
{
    public function handle(): int
    {
        $handle = config('agentic.page_builder_fieldset');

        if (! $fieldset = Fieldset::find($handle)) {
            $this->error("{$handle} fieldset not found.");

            return self::FAILURE;
        }

        if (! $field = $fieldset->fields()->all()->get($handle)) {
            $this->error("{$handle} field not found in fieldset.");

            return self::FAILURE;
        }

        $lines = [
            '# Page-builder section reference',
            '',
            '_Generated by `php artisan content:catalog`. Do not hand-edit._',
            '',
            'These are the only page-builder sections you may use, with their fields. Use exactly',
            'these handles, and for choice fields use exactly one of the options listed.',
            '',
        ];

        foreach ($this->flattenSets($field->get('sets', [])) as $handle => $set) {
            $lines[] = '## '.($set['display'] ?? $handle)." (`{$handle}`)";
            if (! empty($set['instructions'])) {
                $lines[] = '';
                $lines[] = $set['instructions'];
            }
            $lines[] = '';

            $lines = array_merge($lines, $this->fieldLines($set['fields'] ?? [], 0));

            $lines[] = '';
        }

        $out = config('agentic.catalog_path');
        File::put(base_path($out), implode("\n", $lines)."\n");
        $this->info("Wrote {$out}");

        return self::SUCCESS;
    }

    /**
     * One markdown bullet per field, recursing into replicator sets and
     * group/grid children so nested building blocks are catalogued too.
     *
     * @param  array<int, array<string, mixed>>  $fields
     * @return array<int, string>
     */
    private function fieldLines(array $fields, int $depth): array
    {
        $lines = [];
        $pad = str_repeat('    ', $depth);

        foreach ((new Fields($fields))->all() as $handle => $field) {
            $line = "{$pad}- `{$handle}` — ".$field->type().($field->isRequired() ? ' (required)' : '');

            $options = $field->get('options', []);
            if (! empty($options)) {
                $keys = array_is_list($options) ? $options : array_keys($options);
                $line .= '; options: '.implode(', ', $keys);
            }

            $lines[] = $line;

            if ($field->type() === 'replicator') {
                foreach ($this->flattenSets($field->get('sets', [])) as $subHandle => $subSet) {
                    $display = $subSet['display'] ?? null;
                    $lines[] = "{$pad}    - items of type `{$subHandle}`".($display ? " ({$display})" : '').', with:';
                    $lines = array_merge($lines, $this->fieldLines($subSet['fields'] ?? [], $depth + 2));
                }
            } elseif (in_array($field->type(), ['group', 'grid'], true)) {
                $lines = array_merge($lines, $this->fieldLines($field->get('fields', []), $depth + 1));
            }
        }

        return $lines;
    }

    /**
     * Flatten a replicator's grouped `sets` config to [setHandle => setConfig].
     *
     * @param  array<string, mixed>  $sets
     * @return array<string, array<string, mixed>>
     */
    private function flattenSets(array $sets): array
    {
        $flat = [];

        foreach ($sets as $handle => $config) {
            if (isset($config['sets']) && is_array($config['sets'])) {
                foreach ($config['sets'] as $setHandle => $setConfig) {
                    $flat[$setHandle] = $setConfig;
                }
            } else {
                $flat[$handle] = $config;
            }
        }

        return $flat;
    }
}
